application: ranked-voting
version: dev
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/ballot-64.png
  upload: static/ballot-64.png

- url: /create
  script: pages.py
  login: required

- url: /list
  script: pages.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /([^/]+)/vote
  script: pages.py
  login: required

- url: /.*
  script: pages.py
